import {StyleSheet} from "react-native";

const homeScreenStyles = StyleSheet.create({
    starBox:{
        margin: 15,
        marginTop: 5,
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
    },
    levelBox:{
        padding: 8,
        margin: 15,
        borderStyle: "solid",
        borderWidth: 2,
        borderRadius:5,
        borderColor: "gray",
        backgroundColor: "#ffffff",
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'column'
    },
    nameText:{
        width: '80%',
        fontSize: 28,
        color: '#6ccff6',
        fontWeight: 400,
        textAlign: "left",
    },
    levelingBox:{
        flex: .1,
        width: '80%',
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    headerText: {
        margin: 12,
        fontSize: 32,
        fontWeight: "600",
        textAlign: 'center',
    },
    levelText:{
        fontSize: 24,
        width: '50%',
        color: '#6ccff6',
        fontWeight: 400,
        textAlign: 'left',
        paddingVertical: 5,
    },
    pointText:{
        fontSize: 20,
        width: '50%',
        color: '#6ccff6',
        fontWeight: 300,
        textAlign: 'right',
        paddingVertical: 8,
    },
    progressBox:{
        marginBottom: 20,
        flex: .2,
        width: '80%',
        flexDirection: 'row',
    },
    progressBarBackground:{
        position: 'absolute',
        height: 20,
        width: '100%',
        backgroundColor: '#ffffff',
        borderColor: '#000000',
        borderWidth: 2,
        borderRadius: 5,
    },
    progressBar:{               // This styling has been added directly into homeScreen.js to control the width
        //position: 'absolute',
        //height: 20,
        //width: '50%',
        //backgroundColor: '#6ccff6',
        //borderColor: '#000000',
        //borderWidth: 2,
        //borderRadius: 5,
    },
    mainButtonBox: {
        width: '100%',
        flex: 2,
        flexDirection: 'column',
        marginVertical: 10,
        alignContent: 'center',
        alignItems: 'center',
    },
    mainButton: {
        marginVertical: 16,
        margin: 8,
        height: 60,
        backgroundColor: "#6ccff6",
        color: "black",
        width: "80%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 10,
    },
    mainButtonText: {
        color: "#ffffff",
        fontWeight: "600",
        fontSize: 18,
        alignSelf: "center",
    },
    star:{
        margin: 10
    },
    centeredView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 22,
    },
    modalView: {
        width: "75%",
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    popupButton: {
        borderRadius: 20,
        padding: 10,
        elevation: 2,
    },
    buttonClose: {
        backgroundColor: '#2196F3',
    },
    popupTextStyle: {
        color: 'black',
        fontWeight: 'bold',
        fontSize: 25,
        fontStyle: "italic",
        textAlign: 'left',
        marginLeft: 10,
    },
});

export default homeScreenStyles;